package movieTicketInterfaceApp;


/**
* movieTicketInterfaceApp/movieTicketInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from movieTicketInterface.idl
* Monday, March 6, 2023 3:41:32 o'clock PM EST
*/

public abstract class movieTicketInterfacePOA extends org.omg.PortableServer.Servant
 implements movieTicketInterfaceApp.movieTicketInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addMovieSlots", new java.lang.Integer (0));
    _methods.put ("removeMovieSlots", new java.lang.Integer (1));
    _methods.put ("listMovieShowAvailability", new java.lang.Integer (2));
    _methods.put ("bookMovieTickets", new java.lang.Integer (3));
    _methods.put ("getBookingSchedule", new java.lang.Integer (4));
    _methods.put ("cancelMovieTickets", new java.lang.Integer (5));
    _methods.put ("exchangeTickets", new java.lang.Integer (6));
    _methods.put ("shutdown", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // movieTicketInterfaceApp/movieTicketInterface/addMovieSlots
       {
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int bookingCapacity = in.read_long ();
         String $result = null;
         $result = this.addMovieSlots (movieID, movieName, bookingCapacity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // movieTicketInterfaceApp/movieTicketInterface/removeMovieSlots
       {
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         String $result = null;
         $result = this.removeMovieSlots (movieID, movieName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // movieTicketInterfaceApp/movieTicketInterface/listMovieShowAvailability
       {
         String movieName = in.read_string ();
         String $result = null;
         $result = this.listMovieShowAvailability (movieName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // movieTicketInterfaceApp/movieTicketInterface/bookMovieTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int noOfTickets = in.read_long ();
         String $result = null;
         $result = this.bookMovieTickets (customerID, movieID, movieName, noOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // movieTicketInterfaceApp/movieTicketInterface/getBookingSchedule
       {
         String customerID = in.read_string ();
         String $result = null;
         $result = this.getBookingSchedule (customerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // movieTicketInterfaceApp/movieTicketInterface/cancelMovieTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int noOfTickets = in.read_long ();
         String $result = null;
         $result = this.cancelMovieTickets (customerID, movieID, movieName, noOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // movieTicketInterfaceApp/movieTicketInterface/exchangeTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String new_movieID = in.read_string ();
         String new_movieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.exchangeTickets (customerID, movieID, new_movieID, new_movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // movieTicketInterfaceApp/movieTicketInterface/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:movieTicketInterfaceApp/movieTicketInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public movieTicketInterface _this() 
  {
    return movieTicketInterfaceHelper.narrow(
    super._this_object());
  }

  public movieTicketInterface _this(org.omg.CORBA.ORB orb) 
  {
    return movieTicketInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class movieTicketInterfacePOA
