package movieTicketInterfaceApp;


/**
* movieTicketInterfaceApp/movieTicketInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from movieTicketInterface.idl
* Monday, March 6, 2023 3:41:32 o'clock PM EST
*/

public interface movieTicketInterfaceOperations 
{
  String addMovieSlots (String movieID, String movieName, int bookingCapacity);
  String removeMovieSlots (String movieID, String movieName);
  String listMovieShowAvailability (String movieName);
  String bookMovieTickets (String customerID, String movieID, String movieName, int noOfTickets);
  String getBookingSchedule (String customerID);
  String cancelMovieTickets (String customerID, String movieID, String movieName, int noOfTickets);
  String exchangeTickets (String customerID, String movieID, String new_movieID, String new_movieName, int numberOfTickets);
  void shutdown ();
} // interface movieTicketInterfaceOperations
