package movieTicketInterfaceApp;

/**
* movieTicketInterfaceApp/movieTicketInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from movieTicketInterface.idl
* Monday, March 6, 2023 3:41:32 o'clock PM EST
*/

public final class movieTicketInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public movieTicketInterfaceApp.movieTicketInterface value = null;

  public movieTicketInterfaceHolder ()
  {
  }

  public movieTicketInterfaceHolder (movieTicketInterfaceApp.movieTicketInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = movieTicketInterfaceApp.movieTicketInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    movieTicketInterfaceApp.movieTicketInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return movieTicketInterfaceApp.movieTicketInterfaceHelper.type ();
  }

}
