package movieTicketInterfaceApp;


/**
* movieTicketInterfaceApp/movieTicketInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from movieTicketInterface.idl
* Monday, March 6, 2023 3:41:32 o'clock PM EST
*/

public interface movieTicketInterface extends movieTicketInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface movieTicketInterface
